sudo: required
services:
  - docker

before_install:
  - docker build -t rnaikan/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rnaikan/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-800945530468"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
